# Generated by Django 2.2.5 on 2019-09-29 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Identificador')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Apellidos')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Foto')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('profession', models.CharField(max_length=255, verbose_name='Profesión')),
                ('about_me', models.TextField(verbose_name='Sobre mí')),
                ('location', models.CharField(max_length=64, verbose_name='Ubicación')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código postal')),
                ('summary', models.CharField(max_length=255, verbose_name='Resumen')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Teléfono')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Correo electrónico')),
                ('website', models.URLField(db_index=True, verbose_name='Sitio web')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Posición')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de renuncia')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.Company', verbose_name='Compañía')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.Network', verbose_name='Red social')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Habilidad')),
                ('percentage', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Porcentaje de experiencia')),
                ('years', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Años de experiencia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.SkillType', verbose_name='Tipo de habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('searches', models.PositiveIntegerField(default=0, verbose_name='Búsquedas')),
                ('publication_views', models.PositiveIntegerField(default=0, verbose_name='Visitas en publicaciones')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=64, verbose_name='Título o certificado')),
                ('start_year', models.PositiveSmallIntegerField(default=0, verbose_name='Año de inicio')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Año de egreso')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Cursando')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.School', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
            },
        ),
    ]
