# Generated by Django 2.2.5 on 2019-09-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('excerpt', models.CharField(blank=True, max_length=140, null=True, verbose_name='Resumen')),
                ('thumbnail', models.ImageField(blank=True, help_text='La imagen debe tener una proporción 1:1, de preferencia 500x500', null=True, upload_to='thumbs', verbose_name='Portada')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
